[package]
name = "broken-app"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = "0.5"

[profile.release]
# do all optimization but keep debug symbols
debug = "line-tables-only"

[[bench]]
name = "baseline"
harness = false

[[bench]]
name = "criterion"
harness = false
